### ISSUE TITLE
resize.sh実行時にエラー

### ISSUE THREAD

**Issue by mochan-tk** [ufoo68/linedc-ticket-liff#3]
EBS volumeのresizeスクリプトがまた変わっているようで...
https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html

**Comment by ufoo68** [comment]
おうふw

**Comment by mochan-tk** [comment]
今ドキュメントに記載されているスクリプトに変えたら動きますー
↓↓
https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html

**Comment by ufoo68** [comment]
ありがとうございます。もし可能であればprいただけますとw
